#include "led_app.h"
void led_proc(void)
{
	if(lcdmode==0)
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,RESET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	else
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	
	
	if(tim_ic_val[0]>para_arr[1])
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,RESET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	else
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	
	
	if(tim_ic_val[1]>para_arr[1])
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,RESET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	else
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	
if(lcdmode==1)
{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
}
	
if(lcdmode==2)
{
		if(recd_arr[0]>=3||recd_arr[1]>=3)
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_15,RESET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
	else
	{
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,SET);
		HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15,SET);
		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,RESET);
	}
}
}
